on: [push]

jobs:
  update_readme_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Updates_README
    steps:
      - uses: actions/checkout@v3
      - name: Updates_README
        uses: kerong2002/github_action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMITTER_USERNAME: "kerong2002"
          COMMITTER_EMAIL: "krameri120@gmail.com"
          COMMIT_REPO: "Leetcode"
          COMMIT_OWNER: "kerong2002"
          COMMIT_PATH: "C++"
